version: '2'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - public
    depends_on:
      - proxy
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - API_HOST
      - API_PORT
      - MONITOR_HOST
      - MONITOR_PORT
      - PROXY_HOST
      - PROXY_PORT
