version: '2'
services:
  swagger:
    image: ${SWAGGER_IMAGE}
    ports:
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    networks:
      - public
    depends_on:
      - api
    environment:
      - API_URL
