version: '2'
networks:
  rest:
    driver: bridge
services:
  api:
    image: ${API_IMAGE}
    expose:
      - ${API_PORT}
    networks:
      - rest
    depends_on:
      - db
    environment:
      PGRST_DB_ANON_ROLE: ${API_ANON_ROLE}
      PGRST_DB_SCHEMA: ${API_SCHEMA}
      PGRST_DB_URI: postgres://${DB_USER}:${DB_SECRET}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      PGRST_JWT_AUD: ${API_AUTH_ROLE}
      PGRST_JWT_SECRET: ${API_SECRET}
  db:
    image: ${DB_IMAGE}
    networks:
      - rest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_SECRET}
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
      args:
        - BUILD_CONTEXT
    ports:
      - "${SECURE_PORT}:${PROXY_PORT}"
    networks:
      - rest
    depends_on:
      - api
  status:
    build:
      context: .
      dockerfile: Dockerfile.status
    expose:
      - ${STATUS_PORT}
    networks:
      - rest
    env_file: .env
