version: '2'
services:
  task:
    build:
      context: .
      dockerfile: Dockerfile.task
    networks:
      - stack
    depends_on:
      - proxy
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_TASK
      - DB_SECRET
