version: '2'
networks:
  stack:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
services:
  api:
    image: ${API_IMAGE}
    expose:
      - ${API_PORT}
    networks:
      - stack
    depends_on:
      - db
    environment:
      PGRST_DB_ANON_ROLE: ${API_ANON_ROLE}
      PGRST_DB_SCHEMA: ${API_SCHEMA}
      PGRST_DB_URI: postgres://${DB_USER}:${DB_SECRET}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      PGRST_JWT_AUD: ${COMPOSE_PROJECT_NAME}
      PGRST_JWT_SECRET: ${API_SECRET}
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - stack
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_SECRET}
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "${SECURE_PORT}:${PROXY_PORT}"
    networks:
      - stack
    depends_on:
      - api
  status:
    build:
      context: .
      dockerfile: Dockerfile.status
    expose:
      - ${STATUS_PORT}
    networks:
      - stack
    env_file: .env
