version: '2'
networks:
  private:
    driver: bridge
  public:
    driver: bridge
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - ${API_PORT}
    networks:
      - private
      - public
    depends_on:
      - db
    environment:
      PGRST_DB_ANON_ROLE: ${API_ANON_ROLE}
      PGRST_DB_SCHEMA: ${API_SCHEMA}
      PGRST_DB_URI: postgres://${DB_USER}:${DB_SECRET}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      PGRST_JWT_AUD: ${COMPOSE_PROJECT_NAME}
      PGRST_JWT_SECRET: ${API_SECRET}
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    expose:
      - ${DB_PORT}
    networks:
      - private
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_SECRET}
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    expose:
      - ${MONITOR_PORT}
    networks:
      - private
      - public
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "${SECURE_PORT}:${PROXY_PORT}"
    networks:
      - public
    depends_on:
      - api
      - monitor
