FROM node:10-alpine

RUN apk add -q --update --no-cache \
	bash curl jq shadow tini && \
	groupadd -g 777 monitor && \
	useradd -r -g 777 -u 777 -s /sbin/nologin monitor

WORKDIR /opt/gurumojo

COPY lib/monitor/package*.json ./
RUN npm ci

COPY bin bin
COPY etc etc
COPY .env .env
COPY lib/monitor .
COPY lib/*.js lib/

RUN chown monitor etc

ENV CONTAINER_PRE=bin/monitor-init
ENV CONTAINER_CMD="node server"

USER monitor
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["bin/tini-init"]
