FROM postgrest/postgrest:v5.2.0

RUN apt-get -qq update && \
    apt-get -qq install -y --no-install-recommends \
		curl jq && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt/gurumojo

COPY bin bin
COPY etc etc
COPY .env .env

ENV CONTAINER_PRE=bin/api-init
ENV CONTAINER_CMD="postgrest /etc/postgrest.conf"

CMD ["bin/container-init"]
