version: '2'
networks:
  drone:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.041.0/24
        gateway: 172.16.041.1
  private:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.141.0/24
        gateway: 172.16.141.1
  public:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.241.0/24
        gateway: 172.16.241.1
