FROM node:10-alpine

RUN apk add -q --update --no-cache \
	bash curl jq tini

WORKDIR /opt/gurumojo

COPY lib/monitor/package*.json ./
RUN npm ci

COPY bin bin
COPY etc etc
COPY .env .env
COPY lib/monitor .
COPY lib/*.js lib/

RUN chown node etc

ENV CONTAINER_PRE=bin/monitor-init
ENV CONTAINER_CMD="node server"

USER node
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["bin/tini-init"]
