version: '2'
services:
  api:
    ports:
      - "${SERVICE_PORT}:${API_PORT}"
  db:
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./var/data:/var/lib/postgresql/data
  proxy:
    volumes:
      - ./var/log/nginx:/var/log/nginx
  status:
    ports:
      - "${SIDECAR_PORT}:${STATUS_PORT}"
    volumes:
      - ./var/run/status:/var/run/status
  test:
    volumes:
      - ./var/test/coverage:/opt/gurumojo/coverage
